# app-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_USERNAME: YWRtaW4=              # base64 of "admin"
  DB_PASSWORD: UzNjdXIzUEBzc3cwcmQh # base64 of "S3cur3P@ssw0rd!"
  DB_NAME: bXlhcHBfZGI=             # base64 of "myapp_db"
  API_KEY: c3VwZXItc2VjcmV0LWtleQ== # base64 of "super-secret-key"