apiVersion: v1
kind: Service
metadata:
  name: website-service
  namespace: my-website
spec:
  selector:
    app: website
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80